trigger:
- none

# Replace 'Test Nix' with the name of the Agent Pool in Azure DevOps.
pool:
  name: 'Test Nix'
  demands:
  - agent.name -equals nix-test-vm

variables:
  nodeScript: 'index.js'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    # Use the desired Node.js version
    version: '20.x' 

- script: |
    echo "Current working directory: $(System.DefaultWorkingDirectory)"
    node $(nodeScript) | tee output.txt
  displayName: 'Run Simple Node.js Program'
  env:
    # Set an environment variable as a simple test
    PIPELINE_ENV_TEST: 'Success'

- script: |
    if grep -q "Node.js Version" output.txt; then
      echo "##vso[task.setvariable variable=NodeRunStatus]SUCCESS"
      echo "Node script execution confirmed."
    else
      echo "##vso[task.setvariable variable=NodeRunStatus]FAILURE"
      echo "Node script execution FAILED to find expected output."
      exit 1
    fi
  displayName: 'Check Script Output'

- script: |
    echo "Node Run Status is: $(NodeRunStatus)"
    if [ "$(NodeRunStatus)" != "SUCCESS" ]; then
        exit 1
    fi
  displayName: 'Final Status Check'

- script: |
    cat /proc/self/status | grep NoNewPrivs
  displayName: 'Check NoNewPrivileges Status'

- script: |
    sudo cp config.nix /etc/nixos/configuration.nix
    echo "Copied config.nix to /etc/nixos/configuration.nix"
  displayName: 'Copy NixOS Configuration'

- script: |
    sudo systemctl start nixos-apply-config
    echo "NixOS configuration applied successfully"
  displayName: 'Apply NixOS Configuration'